- name: Update homebrew and upgrade all packages
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/home/{{ ansible_user }}/.linuxbrew/bin"
    update_homebrew: yes
    upgrade_all: yes
  become: false
  become_user: "{{ ansible_user }}"
  ignore_errors: yes

- name: "brew install packages"
  become: false
  become_user: "{{ ansible_user }}"
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/home/{{ ansible_user }}/.linuxbrew/bin"
    name: "{{ item }}"
    state: present # Ensure that the package is present
  loop:
    - cmake
    - gcc
    - ruby
    - ruby-install
    - act # github action
    - angle-grinder
    - ansible
    - autojump
    - awscli
    - bat
    - btop
    - coreutils
    - curl
    - croc # send files p2p
    - dfc
    - diff-so-fancy
    - fd
    - fpp
    - freetype # for python matplotlib
    - fzf
    - gcc
    - git
    - git-delta
    - gh # github cli
    - glow
    - grc
    - htop
    - hugo
    - httpie
    - hub
    - lazygit
    - lf # ranger clone
    - lnav
    - lsd
    - mdcat
    - midnight-commander
    - mycli
    - ncdu
    - nvim
    - node
    - openssh
    - p7zip
    - pgcli
    - pyenv
    - pyenv-virtualenv
    - ranger
    - rbenv
    - ripgrep
    - sad
    - sk
    - starship
    - task
    - the_silver_searcher
    - thefuck
    - tig
    - tldr
    - tmux
    - tree
    - urlview
    - vim
    - viu
    - xclip
    - yazi
    - yt-dlp
    - yq
    - zsh
    - zoxide
    - jstkdng/programs/ueberzugpp # used for image preview by yazi
  ignore_errors: yes

- name: "homebrew add tap monkeys-audio"
  shell: "[[ -f /home/linuxbrew/.linuxbrew/bin/brew ]] && /home/linuxbrew/.linuxbrew/bin/brew tap fernandotcl/homebrew-fernandotcl || ([[ -f /home/{{ ansible_user }}/.linuxbrew/bin/brew ]] && /home/{{ ansible_user }}/.linuxbrew/bin/brew tap fernandotcl/homebrew-fernandotcl)"
  args:
    executable: /bin/bash
  become: false
  become_user: "{{ ansible_user }}"
  ignore_errors: yes

- name: "homebrew monkeys-audio"
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/home/{{ ansible_user }}/.linuxbrew/bin"
    name: [monkeys-audio]
    state: present
  become: false
  become_user: "{{ ansible_user }}"
  ignore_errors: yes
