- name: Install NFS Server
  apt:
    name: nfs-kernel-server
    state: present
  become: true

- name: Ensure existing folders have correct permissions
  file:
    path: "{{ item.value }}"
    state: directory
    owner: "1000"
    group: "1000"
  loop: "{{ storage_map[project_dir] | default({}) | dict2items }}"
  when: storage_map[project_dir] is defined
  become: true

- name: Configure /etc/exports
  template:
    src: exports.j2
    dest: /etc/exports
  become: true
  notify: Reload NFS
